const TEMPERATURE_ACTION = 'TEMPERATURE';
const TIME_ACTION = 'TIME';
const GEOMETRY_ACTION = 'GEOMETRY';
const COOKING_ACTION = 'COOKING';

export const actionTypes = {TEMPERATURE_ACTION, TIME_ACTION, GEOMETRY_ACTION, COOKING_ACTION};

